### ISSUE TITLE
After restarting Swift server, prep phase for SwiftPushArtefact fails

### ISSUE THREAD

**Issue by autumn-cpt** [devops-csmake/csmake-swift-provider#8]
```
SwiftPushArtefact@actual-push-cc-docker-station: EXCEPTION: Attempt to execute step 'actual-push-cc-docker-station' in phase 'prep' failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Csmake/CliDriver.py", line 824, in launchStep
    result = method(stepdict)
  File "/usr/lib/python2.7/dist-packages/CsmakeSwiftProvider/CsmakeModules/SwiftPushArtefact.py", line 81, in prep
    SwiftProvider.ensureContainer(client, containerName)
  File "/usr/lib/python2.7/dist-packages/CsmakeSwiftProvider/SwiftProvider.py", line 70, in ensureContainer
    client.put_container(container, result)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1947, in put_container
    query_string=query_string)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1857, in _retry
    service_token=self.service_token, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1165, in put_container
    raise ClientException.from_response(resp, 'Container PUT failed', body)
ClientException: Container PUT failed: http://10.12.0.222:8080/v1/AUTH_cc/artifacts 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.< (txn: txaede5fa2c0064f94a3954-0060df60ee)
` EXCEPTION: Attempt to execute step actual-push-cc-docker-station failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Csmake/CliDriver.py", line 862, in launchStep
    raise e
ClientException: Container PUT failed: http://10.12.0.222:8080/v1/AUTH_cc/artifacts 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.< (txn: txaede5fa2c0064f94a3954-0060df60ee)
```

**Comment by autumnpat** [comment]
This was a swift configuration issue, resolution is to verify rsync is configured properly
